# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20161226_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='message',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='ReportMessages',
        ),
    ]
