language: python
python:
  - "2.7"
  - pypy

before-script:
  - sudo rm -rf couchbase_ffi/_lcb.h
  
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

# command to run tests
script:
  - coverage run -p --source='.' manage.py test
  - coverage combine

after_success:
  - coveralls