# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_categories',
            field=models.ManyToManyField(to='category.Category'),
        ),
    ]
