# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20161213_2152'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_categories',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_categories',
            field=models.ManyToManyField(to='posts.Category'),
        ),
    ]
