# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 01:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20161221_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reputation',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
